const provinceVN = [
  {
    name: "Hà Nội",
    slug: "ha-noi",
    type: "thanh-pho",
    name_with_type: "Thành phố Hà Nội",
    code: "01",
    region: "Miền Bắc",
  },
  {
    name: "Hà Giang",
    slug: "ha-giang",
    type: "tinh",
    name_with_type: "Tỉnh Hà Giang",
    code: "02",
    region: "Miền Bắc",
  },
  {
    name: "Cao Bằng",
    slug: "cao-bang",
    type: "tinh",
    name_with_type: "Tỉnh Cao Bằng",
    code: "04",
    region: "Miền Bắc",
  },
  {
    name: "Bắc Kạn",
    slug: "bac-kan",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Kạn",
    code: "06",
    region: "Miền Bắc",
  },
  {
    name: "Tuyên Quang",
    slug: "tuyen-quang",
    type: "tinh",
    name_with_type: "Tỉnh Tuyên Quang",
    code: "08",
    region: "Miền Bắc",
  },
  {
    name: "Lào Cai",
    slug: "lao-cai",
    type: "tinh",
    name_with_type: "Tỉnh Lào Cai",
    code: "10",
    region: "Miền Bắc",
  },
  {
    name: "Điện Biên",
    slug: "dien-bien",
    type: "tinh",
    name_with_type: "Tỉnh Điện Biên",
    code: "11",
    region: "Miền Bắc",
  },
  {
    name: "Lai Châu",
    slug: "lai-chau",
    type: "tinh",
    name_with_type: "Tỉnh Lai Châu",
    code: "12",
    region: "Miền Bắc",
  },
  {
    name: "Sơn La",
    slug: "son-la",
    type: "tinh",
    name_with_type: "Tỉnh Sơn La",
    code: "14",
    region: "Miền Bắc",
  },
  {
    name: "Yên Bái",
    slug: "yen-bai",
    type: "tinh",
    name_with_type: "Tỉnh Yên Bái",
    code: "15",
    region: "Miền Bắc",
  },
  {
    name: "Hoà Bình",
    slug: "hoa-binh",
    type: "tinh",
    name_with_type: "Tỉnh Hoà Bình",
    code: "17",
    region: "Miền Bắc",
  },
  {
    name: "Thái Nguyên",
    slug: "thai-nguyen",
    type: "tinh",
    name_with_type: "Tỉnh Thái Nguyên",
    code: "19",
    region: "Miền Bắc",
  },
  {
    name: "Lạng Sơn",
    slug: "lang-son",
    type: "tinh",
    name_with_type: "Tỉnh Lạng Sơn",
    code: "20",
    region: "Miền Bắc",
  },
  {
    name: "Quảng Ninh",
    slug: "quang-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Ninh",
    code: "22",
    region: "Miền Bắc",
  },
  {
    name: "Bắc Giang",
    slug: "bac-giang",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Giang",
    code: "24",
    region: "Miền Bắc",
  },
  {
    name: "Phú Thọ",
    slug: "phu-tho",
    type: "tinh",
    name_with_type: "Tỉnh Phú Thọ",
    code: "25",
    region: "Miền Bắc",
  },
  {
    name: "Vĩnh Phúc",
    slug: "vinh-phuc",
    type: "tinh",
    name_with_type: "Tỉnh Vĩnh Phúc",
    code: "26",
    region: "Miền Bắc",
  },
  {
    name: "Bắc Ninh",
    slug: "bac-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Ninh",
    code: "27",
    region: "Miền Bắc",
  },
  {
    name: "Hải Dương",
    slug: "hai-duong",
    type: "tinh",
    name_with_type: "Tỉnh Hải Dương",
    code: "30",
    region: "Miền Bắc",
  },
  {
    name: "Hải Phòng",
    slug: "hai-phong",
    type: "thanh-pho",
    name_with_type: "Thành phố Hải Phòng",
    code: "31",
    region: "Miền Bắc",
  },
  {
    name: "Hưng Yên",
    slug: "hung-yen",
    type: "tinh",
    name_with_type: "Tỉnh Hưng Yên",
    code: "33",
    region: "Miền Bắc",
  },
  {
    name: "Thái Bình",
    slug: "thai-binh",
    type: "tinh",
    name_with_type: "Tỉnh Thái Bình",
    code: "34",
    region: "Miền Bắc",
  },
  {
    name: "Hà Nam",
    slug: "ha-nam",
    type: "tinh",
    name_with_type: "Tỉnh Hà Nam",
    code: "35",
    region: "Miền Bắc",
  },
  {
    name: "Nam Định",
    slug: "nam-dinh",
    type: "tinh",
    name_with_type: "Tỉnh Nam Định",
    code: "36",
    region: "Miền Bắc",
  },
  {
    name: "Ninh Bình",
    slug: "ninh-binh",
    type: "tinh",
    name_with_type: "Tỉnh Ninh Bình",
    code: "37",
    region: "Miền Bắc",
  },
  {
    name: "Thanh Hóa",
    slug: "thanh-hoa",
    type: "tinh",
    name_with_type: "Tỉnh Thanh Hóa",
    code: "38",
    region: "Miền Trung",
  },
  {
    name: "Nghệ An",
    slug: "nghe-an",
    type: "tinh",
    name_with_type: "Tỉnh Nghệ An",
    code: "40",
    region: "Miền Trung",
  },
  {
    name: "Hà Tĩnh",
    slug: "ha-tinh",
    type: "tinh",
    name_with_type: "Tỉnh Hà Tĩnh",
    code: "42",
    region: "Miền Trung",
  },
  {
    name: "Quảng Bình",
    slug: "quang-binh",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Bình",
    code: "44",
    region: "Miền Trung",
  },
  {
    name: "Quảng Trị",
    slug: "quang-tri",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Trị",
    code: "45",
    region: "Miền Trung",
  },
  {
    name: "Thừa Thiên Huế",
    slug: "thua-thien-hue",
    type: "tinh",
    name_with_type: "Tỉnh Thừa Thiên Huế",
    code: "46",
    region: "Miền Trung",
  },
  {
    name: "Đà Nẵng",
    slug: "da-nang",
    type: "thanh-pho",
    name_with_type: "Thành phố Đà Nẵng",
    code: "48",
    region: "Miền Trung",
  },
  {
    name: "Quảng Nam",
    slug: "quang-nam",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Nam",
    code: "49",
    region: "Miền Trung",
  },
  {
    name: "Quảng Ngãi",
    slug: "quang-ngai",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Ngãi",
    code: "51",
    region: "Miền Trung",
  },
  {
    name: "Bình Định",
    slug: "binh-dinh",
    type: "tinh",
    name_with_type: "Tỉnh Bình Định",
    code: "52",
    region: "Miền Trung",
  },
  {
    name: "Phú Yên",
    slug: "phu-yen",
    type: "tinh",
    name_with_type: "Tỉnh Phú Yên",
    code: "54",
    region: "Miền Trung",
  },
  {
    name: "Khánh Hòa",
    slug: "khanh-hoa",
    type: "tinh",
    name_with_type: "Tỉnh Khánh Hòa",
    code: "56",
    region: "Miền Trung",
  },
  {
    name: "Ninh Thuận",
    slug: "ninh-thuan",
    type: "tinh",
    name_with_type: "Tỉnh Ninh Thuận",
    code: "58",
    region: "Miền Trung",
  },
  {
    name: "Bình Thuận",
    slug: "binh-thuan",
    type: "tinh",
    name_with_type: "Tỉnh Bình Thuận",
    code: "60",
    region: "Miền Trung",
  },
  {
    name: "Kon Tum",
    slug: "kon-tum",
    type: "tinh",
    name_with_type: "Tỉnh Kon Tum",
    code: "62",
    region: "Miền Trung",
  },
  {
    name: "Gia Lai",
    slug: "gia-lai",
    type: "tinh",
    name_with_type: "Tỉnh Gia Lai",
    code: "64",
    region: "Miền Trung",
  },
  {
    name: "Đắk Lắk",
    slug: "dak-lak",
    type: "tinh",
    name_with_type: "Tỉnh Đắk Lắk",
    code: "66",
    region: "Miền Trung",
  },
  {
    name: "Đắk Nông",
    slug: "dak-nong",
    type: "tinh",
    name_with_type: "Tỉnh Đắk Nông",
    code: "67",
    region: "Miền Trung",
  },
  {
    name: "Lâm Đồng",
    slug: "lam-dong",
    type: "tinh",
    name_with_type: "Tỉnh Lâm Đồng",
    code: "68",
    region: "Miền Trung",
  },
  {
    name: "Bình Phước",
    slug: "binh-phuoc",
    type: "tinh",
    name_with_type: "Tỉnh Bình Phước",
    code: "70",
    region: "Miền Nam",
  },
  {
    name: "Tây Ninh",
    slug: "tay-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Tây Ninh",
    code: "72",
    region: "Miền Nam",
  },
  {
    name: "Bình Dương",
    slug: "binh-duong",
    type: "tinh",
    name_with_type: "Tỉnh Bình Dương",
    code: "74",
    region: "Miền Nam",
  },
  {
    name: "Đồng Nai",
    slug: "dong-nai",
    type: "tinh",
    name_with_type: "Tỉnh Đồng Nai",
    code: "75",
    region: "Miền Nam",
  },
  {
    name: "Bà Rịa Vũng Tàu",
    slug: "ba-ria-vung-tau",
    type: "tinh",
    name_with_type: "Tỉnh Bà Rịa - Vũng Tàu",
    code: "77",
    region: "Miền Nam",
  },
  {
    name: "Hồ Chí Minh",
    slug: "ho-chi-minh",
    type: "thanh-pho",
    name_with_type: "Thành phố Hồ Chí Minh",
    code: "79",
    region: "Miền Nam",
  },
  {
    name: "Long An",
    slug: "long-an",
    type: "tinh",
    name_with_type: "Tỉnh Long An",
    code: "80",
    region: "Miền Nam",
  },
  {
    name: "Tiền Giang",
    slug: "tien-giang",
    type: "tinh",
    name_with_type: "Tỉnh Tiền Giang",
    code: "82",
    region: "Miền Nam",
  },
  {
    name: "Bến Tre",
    slug: "ben-tre",
    type: "tinh",
    name_with_type: "Tỉnh Bến Tre",
    code: "83",
    region: "Miền Nam",
  },
  {
    name: "Trà Vinh",
    slug: "tra-vinh",
    type: "tinh",
    name_with_type: "Tỉnh Trà Vinh",
    code: "84",
    region: "Miền Nam",
  },
  {
    name: "Vĩnh Long",
    slug: "vinh-long",
    type: "tinh",
    name_with_type: "Tỉnh Vĩnh Long",
    code: "86",
    region: "Miền Nam",
  },
  {
    name: "Đồng Tháp",
    slug: "dong-thap",
    type: "tinh",
    name_with_type: "Tỉnh Đồng Tháp",
    code: "87",
    region: "Miền Nam",
  },
  {
    name: "An Giang",
    slug: "an-giang",
    type: "tinh",
    name_with_type: "Tỉnh An Giang",
    code: "89",
    region: "Miền Nam",
  },
  {
    name: "Kiên Giang",
    slug: "kien-giang",
    type: "tinh",
    name_with_type: "Tỉnh Kiên Giang",
    code: "91",
    region: "Miền Nam",
  },
  {
    name: "Cần Thơ",
    slug: "can-tho",
    type: "thanh-pho",
    name_with_type: "Thành phố Cần Thơ",
    code: "92",
    region: "Miền Nam",
  },
  {
    name: "Hậu Giang",
    slug: "hau-giang",
    type: "tinh",
    name_with_type: "Tỉnh Hậu Giang",
    code: "93",
    region: "Miền Nam",
  },
  {
    name: "Sóc Trăng",
    slug: "soc-trang",
    type: "tinh",
    name_with_type: "Tỉnh Sóc Trăng",
    code: "94",
    region: "Miền Nam",
  },
  {
    name: "Bạc Liêu",
    slug: "bac-lieu",
    type: "tinh",
    name_with_type: "Tỉnh Bạc Liêu",
    code: "95",
    region: "Miền Nam",
  },
  {
    name: "Cà Mau",
    slug: "ca-mau",
    type: "tinh",
    name_with_type: "Tỉnh Cà Mau",
    code: "96",
    region: "Miền Nam",
  },
];
export const provinceToRegion = province => {
  const item = provinceVN.find(item => item.name === province);
  if (!item) return province;

  return item;
};
